#!/bin/sh

### BEGIN INIT INFO
# Provides: i2c-hwclock
# Required-Start:
# Required-Stop: umountroot
# Should-Stop:
# X-Start-Before: checkroot
# Default-Start: S
# Default-Stop: 0 1 6
# Short-Description: Restore / save the current clock
# Description:
### END INIT INFO

set -e
case "${1:-}" in
stop|reload|restart|force-reload)
echo "Stopping i2c hwclock: saving system time."
i2c-hwclock save ;;

start)
echo "Starting i2c hwclock: loading system time."
i2c-hwclock load ;;
*)
echo "Usage: ${0:-} {start|stop|status|restart|reload|force-reload}" >&2
exit 1
;;
esac

